require("dotenv").config();
const { neonConfig, Pool } = require("@neondatabase/serverless");
const { PrismaNeon } = require("@prisma/adapter-neon");
const { PrismaClient } = require("@prisma/client");
const ws = require("ws");
const bcrypt = require("bcryptjs");

neonConfig.webSocketConstructor = ws;

const prisma = new PrismaClient({
  adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL }),
});

async function main() {
  console.log("🌱 Seeding database...");

  // Seed settings
  await prisma.setting.createMany({
    data: [
      {
        key: "fine_rate_per_day",
        value: "5",
        description: "Fine amount in ₹ per overdue day",
      },
      {
        key: "borrow_duration_days",
        value: "14",
        description: "Default borrow period in days",
      },
      {
        key: "extension_days",
        value: "7",
        description: "Days added when a borrow is extended",
      },
      {
        key: "max_active_borrows",
        value: "3",
        description: "Max simultaneous borrows per member",
      },
    ],
    skipDuplicates: true,
  });

  // Seed admin user
  const adminPassword = await bcrypt.hash("Admin@2005", 12);
  const admin = await prisma.user.upsert({
    where: { email: "admin@technoindiaeducation.com" },
    update: { passwordHash: adminPassword, name: "Admin" },
    create: {
      name: "Admin",
      email: "admin@technoindiaeducation.com",
      passwordHash: adminPassword,
      role: "admin",
    },
  });

  // Remove old demo admin if it exists
  await prisma.user.deleteMany({ where: { email: "admin@library.com" } });

  // Seed demo librarian
  const librarianPassword = await bcrypt.hash("Librarian@123", 12);
  await prisma.user.upsert({
    where: { email: "librarian@library.com" },
    update: {},
    create: {
      name: "Priya Librarian",
      email: "librarian@library.com",
      passwordHash: librarianPassword,
      role: "librarian",
    },
  });

  // Seed member user
  const memberPassword = await bcrypt.hash("Member@123", 12);
  const memberUser = await prisma.user.upsert({
    where: { email: "member@library.com" },
    update: {},
    create: {
      name: "Rahul Member",
      email: "member@library.com",
      passwordHash: memberPassword,
      role: "member",
    },
  });

  // Seed member profile
  const expiryDate = new Date();
  expiryDate.setFullYear(expiryDate.getFullYear() + 1);

  await prisma.member.upsert({
    where: { userId: memberUser.id },
    update: {},
    create: {
      userId: memberUser.id,
      name: "Rahul Member",
      email: "member@library.com",
      phone: "9876543210",
      membershipNo: "LIB-000001",
      address: "Kolkata, West Bengal",
      membershipType: "basic",
      expiryDate,
      avatarColor: "#ef4444",
    },
  });

  // Seed books
  await prisma.book.createMany({
    data: [
      // ── Programming & CS ──────────────────────────────────────────────
      {
        title: "Clean Code",
        author: "Robert C. Martin",
        isbn: "9780132350884",
        category: "Programming",
        year: 2008,
        description: "Guide to writing clean and maintainable code",
        publisher: "Prentice Hall",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt",
        isbn: "9780201616224",
        category: "Programming",
        year: 1999,
        description: "Classic book for software developers",
        publisher: "Addison Wesley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Introduction to Algorithms",
        author: "Thomas H. Cormen",
        isbn: "9780262033848",
        category: "Algorithms",
        year: 2009,
        description: "Comprehensive algorithms reference",
        publisher: "MIT Press",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
        totalCopies: 6,
        availableCopies: 6,
      },
      {
        title: "Design Patterns",
        author: "Erich Gamma",
        isbn: "9780201633610",
        category: "Software Engineering",
        year: 1994,
        description: "Object oriented design patterns",
        publisher: "Addison Wesley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Data Structures and Algorithms in C++",
        author: "Michael T. Goodrich",
        isbn: "9781118771334",
        category: "Programming",
        year: 2014,
        description: "DSA implementation in C++",
        publisher: "Wiley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781118771334-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Operating System Concepts",
        author: "Abraham Silberschatz",
        isbn: "9781118063330",
        category: "Operating Systems",
        year: 2018,
        description: "Operating systems fundamentals",
        publisher: "Wiley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781118063330-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "Computer Networks",
        author: "Andrew S. Tanenbaum",
        isbn: "9780132126953",
        category: "Networking",
        year: 2010,
        description: "Networking concepts",
        publisher: "Pearson",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780132126953-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Database System Concepts",
        author: "Abraham Silberschatz",
        isbn: "9780073523323",
        category: "Database",
        year: 2011,
        description: "Database systems",
        publisher: "McGraw Hill",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780073523323-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Code Complete",
        author: "Steve McConnell",
        isbn: "9780735619678",
        category: "Software Engineering",
        year: 2004,
        description: "A practical handbook of software construction",
        publisher: "Microsoft Press",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780735619678-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Refactoring",
        author: "Martin Fowler",
        isbn: "9780201485677",
        category: "Software Engineering",
        year: 1999,
        description: "Improving the design of existing code",
        publisher: "Addison Wesley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780201485677-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Domain-Driven Design",
        author: "Eric Evans",
        isbn: "9780321125217",
        category: "Software Engineering",
        year: 2003,
        description: "Tackling complexity in the heart of software",
        publisher: "Addison Wesley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780321125217-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Head First Design Patterns",
        author: "Eric Freeman",
        isbn: "9780596007126",
        category: "Software Engineering",
        year: 2004,
        description: "A brain-friendly guide to design patterns",
        publisher: "OReilly",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780596007126-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      // ── JavaScript ─────────────────────────────────────────────────────
      {
        title: "You Don't Know JS",
        author: "Kyle Simpson",
        isbn: "9781491904244",
        category: "JavaScript",
        year: 2015,
        description: "Deep dive into JavaScript",
        publisher: "OReilly",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781491904244-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "JavaScript: The Good Parts",
        author: "Douglas Crockford",
        isbn: "9780596517748",
        category: "JavaScript",
        year: 2008,
        description: "Essential JavaScript concepts",
        publisher: "OReilly",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780596517748-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Eloquent JavaScript",
        author: "Marijn Haverbeke",
        isbn: "9781593279509",
        category: "JavaScript",
        year: 2018,
        description: "Modern JavaScript guide",
        publisher: "No Starch Press",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781593279509-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      // ── Python ─────────────────────────────────────────────────────────
      {
        title: "Python Crash Course",
        author: "Eric Matthes",
        isbn: "9781593279288",
        category: "Programming",
        year: 2019,
        description: "Beginner Python programming",
        publisher: "No Starch Press",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781593279288-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "Fluent Python",
        author: "Luciano Ramalho",
        isbn: "9781491946008",
        category: "Python",
        year: 2015,
        description: "Advanced Python techniques",
        publisher: "OReilly",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781491946008-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      // ── Web Development ────────────────────────────────────────────────
      {
        title: "Learning React",
        author: "Alex Banks",
        isbn: "9781492051725",
        category: "Web Development",
        year: 2020,
        description: "React development guide",
        publisher: "OReilly",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781492051725-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Fullstack React",
        author: "Anthony Accomazzo",
        isbn: "9780991344628",
        category: "Web Development",
        year: 2017,
        description: "React fullstack development",
        publisher: "Fullstack IO",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780991344628-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Node.js Design Patterns",
        author: "Mario Casciaro",
        isbn: "9781783287314",
        category: "Backend",
        year: 2016,
        description: "Node.js architecture",
        publisher: "Packt",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781783287314-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Building Microservices",
        author: "Sam Newman",
        isbn: "9781492034025",
        category: "Software Engineering",
        year: 2021,
        description: "Designing fine-grained systems",
        publisher: "OReilly",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781492034025-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      // ── AI / ML ────────────────────────────────────────────────────────
      {
        title: "Artificial Intelligence: A Modern Approach",
        author: "Stuart Russell",
        isbn: "9780136042594",
        category: "AI",
        year: 2010,
        description: "Fundamental AI textbook",
        publisher: "Pearson",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780136042594-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "Deep Learning",
        author: "Ian Goodfellow",
        isbn: "9780262035613",
        category: "AI",
        year: 2016,
        description: "Deep learning concepts",
        publisher: "MIT Press",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780262035613-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Pattern Recognition and Machine Learning",
        author: "Christopher M. Bishop",
        isbn: "9780387310732",
        category: "AI",
        year: 2006,
        description: "Classical introduction to machine learning",
        publisher: "Springer",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780387310732-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      // ── System Design ──────────────────────────────────────────────────
      {
        title: "System Design Interview",
        author: "Alex Xu",
        isbn: "9781736049114",
        category: "System Design",
        year: 2020,
        description: "System design preparation",
        publisher: "Independently Published",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781736049114-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Grokking Algorithms",
        author: "Aditya Bhargava",
        isbn: "9781617292231",
        category: "Algorithms",
        year: 2016,
        description: "Visual guide to algorithms",
        publisher: "Manning",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781617292231-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "The Mythical Man-Month",
        author: "Fred Brooks",
        isbn: "9780201835953",
        category: "Software Engineering",
        year: 1995,
        description: "Essays on software engineering",
        publisher: "Addison Wesley",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780201835953-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      // ── Self Improvement / Business ───────────────────────────────────
      {
        title: "Atomic Habits",
        author: "James Clear",
        isbn: "9780735211292",
        category: "Self Improvement",
        year: 2018,
        description: "Habit building",
        publisher: "Avery",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "The Lean Startup",
        author: "Eric Ries",
        isbn: "9780307887894",
        category: "Startup",
        year: 2011,
        description: "Startup methodology",
        publisher: "Crown Business",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Zero to One",
        author: "Peter Thiel",
        isbn: "9780804139298",
        category: "Startup",
        year: 2014,
        description: "Startup thinking",
        publisher: "Crown Business",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        isbn: "9781612680194",
        category: "Self Improvement",
        year: 2011,
        description: "What the rich teach their kids about money",
        publisher: "Plata Publishing",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        isbn: "9781585424337",
        category: "Self Improvement",
        year: 2004,
        description: "Classic personal development book",
        publisher: "Tarcher Perigee",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "How to Win Friends and Influence People",
        author: "Dale Carnegie",
        isbn: "9780671027032",
        category: "Self Improvement",
        year: 1998,
        description: "Timeless guide to dealing with people",
        publisher: "Simon & Schuster",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen R. Covey",
        isbn: "9780743269513",
        category: "Self Improvement",
        year: 2004,
        description: "Powerful lessons in personal change",
        publisher: "Simon & Schuster",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780743269513-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        isbn: "9780374533557",
        category: "Self Improvement",
        year: 2013,
        description: "How two systems drive the way we think",
        publisher: "Farrar Straus Giroux",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Steve Jobs",
        author: "Walter Isaacson",
        isbn: "9781451648539",
        category: "Biography",
        year: 2011,
        description: "The exclusive biography of Steve Jobs",
        publisher: "Simon & Schuster",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      // ── History ─────────────────────────────────────────────────────────
      {
        title: "Sapiens",
        author: "Yuval Noah Harari",
        isbn: "9780062316097",
        category: "History",
        year: 2015,
        description: "History of humankind",
        publisher: "Harper",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Homo Deus",
        author: "Yuval Noah Harari",
        isbn: "9780062464316",
        category: "History",
        year: 2017,
        description: "Future of humanity",
        publisher: "Harper",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "The Art of War",
        author: "Sun Tzu",
        isbn: "9781599869773",
        category: "History",
        year: 2007,
        description: "Ancient Chinese military treatise",
        publisher: "Filiquarian",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      // ── Fiction ─────────────────────────────────────────────────────────
      {
        title: "The Alchemist",
        author: "Paulo Coelho",
        isbn: "9780061122415",
        category: "Fiction",
        year: 1993,
        description: "Inspirational fiction",
        publisher: "HarperOne",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      {
        title: "1984",
        author: "George Orwell",
        isbn: "9780451524935",
        category: "Fiction",
        year: 1949,
        description: "Dystopian novel",
        publisher: "Signet Classics",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        isbn: "9780060935467",
        category: "Fiction",
        year: 1960,
        description: "Classic novel",
        publisher: "Harper Perennial",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        isbn: "9780743273565",
        category: "Fiction",
        year: 1925,
        description: "The tale of the fabulously wealthy Jay Gatsby",
        publisher: "Scribner",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "Brave New World",
        author: "Aldous Huxley",
        isbn: "9780060850524",
        category: "Fiction",
        year: 1932,
        description: "A dystopian social science fiction novel",
        publisher: "Harper Perennial",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        isbn: "9780345391803",
        category: "Fiction",
        year: 1979,
        description: "A comedic science fiction series",
        publisher: "Del Rey",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        isbn: "9780316769174",
        category: "Fiction",
        year: 1951,
        description: "A controversial novel about teenage alienation",
        publisher: "Little Brown",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        isbn: "9780439708180",
        category: "Fiction",
        year: 1998,
        description: "The first book in the Harry Potter series",
        publisher: "Scholastic",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg",
        totalCopies: 6,
        availableCopies: 6,
      },
      {
        title: "The Da Vinci Code",
        author: "Dan Brown",
        isbn: "9780307474278",
        category: "Fiction",
        year: 2003,
        description: "A mystery thriller and detective novel",
        publisher: "Anchor",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
        totalCopies: 5,
        availableCopies: 5,
      },
      // ── Science / Other ────────────────────────────────────────────────
      {
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        isbn: "9780553380163",
        category: "Science",
        year: 1998,
        description: "From the Big Bang to black holes",
        publisher: "Bantam",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
      {
        title: "The Selfish Gene",
        author: "Richard Dawkins",
        isbn: "9780198788607",
        category: "Science",
        year: 2016,
        description: "A landmark work in the field of evolutionary biology",
        publisher: "Oxford University Press",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg",
        totalCopies: 3,
        availableCopies: 3,
      },
      {
        title: "Software Engineering",
        author: "Ian Sommerville",
        isbn: "9780133943030",
        category: "Software Engineering",
        year: 2015,
        description: "Comprehensive software engineering guide",
        publisher: "Pearson",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780133943030-L.jpg",
        totalCopies: 4,
        availableCopies: 4,
      },
    ],
    skipDuplicates: true,
  });

  console.log("✅ Seeding complete!");
  console.log("");
  console.log("Credentials:");
  console.log("  Admin     → admin@library.com     / Admin@123");
  console.log("  Librarian → librarian@library.com / Librarian@123");
  console.log("  Member    → member@library.com    / Member@123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
